# HW2. SQL Basics

## Objectives

In this homework assignment, you will use SQL to store and query a database. You will practice the followings:

 - How to use patterns to find matching information
 - How to use Order By to sort data
 - How to use Set Operators to union/intersect multiple tables
 - How to use Join Opeartor to join multiple tables
 
This assignment has a total of 10 points.

# HomeWork

Suppose you work at a bank as a data analyst. Your main job is to analyze the data stored in their database to find out information that can help the business. Please download the database at this [link](bank.db).

The database has five tables. The following shows their schemas. Primary key attributes are underlined and foreign keys are noted in superscript.
 - Customer = {<span style="text-decoration:underline">customerID</span>, firstName, lastName, income, birthDate}
 - Account = {<span style="text-decoration:underline">accNumber</span>, type, balance, branchNumber<sup>FK-Branch</sup>}
 - Owns = {<span style="text-decoration:underline">customerID</span><sup>FK-Customer</sup>, <span style="text-decoration:underline">accNumber</span><sup>FK-Account</sup>}
 - Transactions = {<span style="text-decoration:underline">transNumber</span>, <span style="text-decoration:underline">accNumber</span><sup>FK-Account</sup>, amount}
 - Employee = {<span style="text-decoration:underline">sin</span>, firstName, lastName, salary, branchNumber<sup>FK-Branch</sup>}
 - Branch = {<span style="text-decoration:underline">branchNumber</span>, branchName, managerSIN<sup>FK-Employee</sup>, budget}

Please run the next two cells after downloading the database, before you start.

In [1]:
%load_ext sql

In [2]:
%sql sqlite:///bank.db

'Connected: @bank.db'

1. (1 point) Suppose you talked with a customer, you remember their name started with 'M', inluded an 'r' and finished with an 'a', but you are not sure about the complete spelling. Please write a SQL query to show the first name and last name of the customers with such first name.

In [3]:
%%sql
SELECT firstName, lastName
FROM Customer
WHERE firstName LIKE 'M%r%a'

 * sqlite:///bank.db
Done.

[('Martha', 'Young'),
 ('Martha', 'Butler'),
 ('Maria', 'Morgan'),
 ('Maria', 'Young')]

2. (1 point) Please write a SQL query to show names of the branches and first name and last name of their managers.

In [4]:
%%sql
SELECT firstName, lastName
FROM Employee, Branch
WHERE sin = managerSIN

 * sqlite:///bank.db
Done.

[('Phillip', 'Edwards'),
 ('Victor', 'Doom'),
 ('Victor', 'Doom'),
 ('Deborah', 'Hernandez'),
 ('Cheryl', 'Thompson')]

3. (2 points) Please write a SQL query to find out employees who are also customers (based on their matching first name and last names).

In [5]:
%%sql
SELECT Employee.firstName, Employee.lastName
FROM Employee, Customer
WHERE Employee.firstName = Customer.firstName and Employee.lastName=Customer.lastName

 * sqlite:///bank.db
Done.

[('Anne', 'Ramirez'),
 ('Steven', 'Johnson'),
 ('Margaret', 'White'),
 ('Amanda', 'White'),
 ('Roy', 'Morris'),
 ('Victor', 'Doom'),
 ('Victor', 'Perez'),
 ('Terry', 'Bailey'),
 ('Gerald', 'Watson'),
 ('Victor', 'Doom'),
 ('Mark', 'Jackson'),
 ('Kathleen', 'Morris'),
 ('Phillip', 'Edwards'),
 ('Ernest', 'Adams'),
 ('Mary', 'Powell'),
 ('Arthur', 'Jones'),
 ('Laura', 'Alexander'),
 ('Willie', 'Jones'),
 ('Anna', 'Cooper'),
 ('Douglas', 'Wright'),
 ('Charles', 'Smith'),
 ('Susan', 'Hayes'),
 ('Justin', 'Mitchell'),
 ('Carl', 'Murphy'),
 ('Victor', 'Doom'),
 ('Amy', 'Ross'),
 ('Ernest', 'Perez'),
 ('Dennis', 'Collins'),
 ('Deborah', 'Hernandez')]

4. (3 points) Please write a SQL query to show account number, account type, account balance, and transaction amount of the accounts with balance higher than 100,000 and transaction amouns higher than 15000, starting by the accounts with the highest transaction amount and highest account balance.

In [6]:
%%sql
SELECT Account.accNumber, Account.type, Account.balance, Transactions.amount
FROM Account, Transactions
WHERE Account.accNumber = Transactions.accNumber and Account.balance > 10000 and Transactions.amount > 15000
ORDER BY Transactions.amount DESC, Account.balance DESC

 * sqlite:///bank.db
Done.

[(9, 'SAV', 132271.23, 114869.79),
 (8, 'BUS', 121267.54, 114680.63),
 (31, 'CHQ', 111209.89, 110249.28),
 (1, 'SAV', 118231.13, 109587.15),
 (25, 'SAV', 105997.07, 109068.54),
 (13, 'CHQ', 112505.84, 108440.2),
 (20, 'CHQ', 107270.59, 108278.46),
 (4, 'BUS', 106503.6, 104550.76),
 (26, 'SAV', 112046.36, 104346.46),
 (6, 'CHQ', 107309.23, 104247.4),
 (18, 'BUS', 103579.69, 103802.18),
 (17, 'CHQ', 103356.07, 103431.57),
 (28, 'CHQ', 112617.97, 102680.84),
 (5, 'CHQ', 105696.04, 101945.4),
 (2, 'CHQ', 100808.03, 100002.19),
 (81, 'CHQ', 107129.47, 99712.38),
 (227, 'CHQ', 109916.78, 98987.65),
 (218, 'BUS', 103650.37, 98757.79),
 (119, 'CHQ', 113473.16, 98480.27),
 (147, 'CHQ', 114094.94, 98155.28),
 (121, 'SAV', 103512.78, 98101.36),
 (187, 'CHQ', 103328.66, 97629.4),
 (165, 'CHQ', 108042.83, 96796.3),
 (138, 'BUS', 104044.22, 96658.35),
 (176, 'CHQ', 113048.79, 96473.74),
 (282, 'SAV', 101063.84, 96430.68),
 (135, 'SAV', 105420.87, 95889.6),
 (198, 'CHQ', 102686.76, 95539.37),
 (272, 'CHQ', 101739.44, 95431.93),
 (191, 'CHQ', 95003.16, 94348.99),
 (164, 'CHQ', 101336.25, 94145.63),
 (140, 'SAV', 99233.93, 93762.52),
 (115, 'BUS', 102857.55, 93549.92),
 (277, 'CHQ', 95702.75, 92555.73),
 (139, 'BUS', 101394.11, 92397.65),
 (59, 'CHQ', 112534.31, 91590.92),
 (245, 'SAV', 95413.18, 91055.62),
 (221, 'BUS', 105068.53, 90728.42),
 (291, 'SAV', 101504.47, 90181.92),
 (275, 'SAV', 95955.98, 89214.12),
 (24, 'CHQ', 93154.91, 87898.67),
 (146, 'SAV', 95876.24, 87796.11),
 (7, 'CHQ', 95358.73, 87687.35),
 (200, 'BUS', 100035.01, 87660.19),
 (130, 'CHQ', 102776.09, 87542.82),
 (67, 'CHQ', 93884.6, 87446.33),
 (56, 'CHQ', 97555.21, 86869.57),
 (107, 'BUS', 102366.95, 86853.53),
 (240, 'BUS', 96635.34, 86743.54),
 (252, 'CHQ', 94530.03, 86529.71),
 (132, 'CHQ', 99950.35, 85893.27),
 (172, 'CHQ', 85165.81, 85481.55),
 (106, 'BUS', 102297.76, 85329.15),
 (158, 'CHQ', 83981.94, 84961.78),
 (142, 'SAV', 86931.71, 84770.37),
 (209, 'BUS', 88574.32, 84723.79),
 (151, 'BUS', 82207.06, 84601.1),
 (137, 'SAV', 76535.96, 84296.1),
 (211, 'CHQ', 94562.36, 83979.86),
 (29, 'CHQ', 94087.32, 83788.17),
 (148, 'CHQ', 100187.85, 83528.49),
 (76, 'CHQ', 86994.95, 83354.2),
 (194, 'SAV', 92152.03, 83308.7),
 (103, 'SAV', 90491.84, 82405.21),
 (259, 'CHQ', 89292.26, 82326.34),
 (64, 'SAV', 87815.69, 82145.19),
 (215, 'BUS', 83349.17, 82042.09),
 (19, 'SAV', 83432.52, 81693.82),
 (149, 'CHQ', 81508.76, 80869.04),
 (206, 'CHQ', 83814.09, 80371.46),
 (89, 'SAV', 97457.14, 79760.09),
 (15, 'CHQ', 78226.03, 79218.74),
 (268, 'SAV', 91951.04, 79173.87),
 (45, 'CHQ', 85737.08, 78925.11),
 (195, 'CHQ', 88554.16, 78781.21),
 (141, 'BUS', 93073.14, 78478.11),
 (162, 'CHQ', 90303.24, 78144.45),
 (279, 'BUS', 88794.87, 78087.45),
 (11, 'CHQ', 90343.03, 77146),
 (102, 'CHQ', 89221.14, 76986.27),
 (38, 'CHQ', 82432.46, 76980.7),
 (237, 'BUS', 91951.43, 76763.14),
 (281, 'CHQ', 80968.75, 76718.54),
 (40, 'SAV', 72419.68, 76617.73),
 (228, 'SAV', 77031.07, 76302.64),
 (57, 'CHQ', 82512.57, 76179.46),
 (293, 'CHQ', 82812.96, 75934.98),
 (171, 'SAV', 94194.62, 75627.02),
 (203, 'CHQ', 80881.13, 75588.51),
 (199, 'BUS', 87161.89, 75295.58),
 (249, 'BUS', 83863.1, 74825.76),
 (160, 'SAV', 87925.09, 74785.12),
 (290, 'BUS', 87236.94, 74720.96),
 (77, 'CHQ', 92207.37, 74642.25),
 (3, 'CHQ', 77231.12, 74568.53),
 (133, 'BUS', 86457.17, 74462.55),
 (190, 'CHQ', 89691.22, 74251.89),
 (27, 'BUS', 81162.08, 73921.87),
 (229, 'CHQ', 81816.87, 73719),
 (232, 'CHQ', 81180.98, 73436.14),
 (22, 'BUS', 78928.42, 73160.22),
 (262, 'CHQ', 82475.58, 72963),
 (253, 'SAV', 74761.19, 72957.76),
 (16, 'BUS', 75390.64, 72546.54),
 (12, 'SAV', 77626.76, 72310.58),
 (111, 'CHQ', 70566.34, 72144.9),
 (128, 'SAV', 73129.43, 72025.84),
 (35, 'SAV', 77214.48, 71961.77),
 (123, 'BUS', 80993.9, 71410.26),
 (32, 'SAV', 83408.19, 70648.44),
 (222, 'SAV', 81498.87, 70560.78),
 (297, 'BUS', 77378.21, 70281.89),
 (202, 'CHQ', 66850.69, 70250.94),
 (269, 'BUS', 79912.41, 70116.03),
 (14, 'CHQ', 73455.1, 69996.29),
 (78, 'SAV', 72742.21, 69868.35),
 (292, 'CHQ', 86090.85, 69771.17),
 (220, 'CHQ', 84329.91, 69592.9),
 (241, 'CHQ', 75723.27, 69362.9),
 (93, 'BUS', 79642.98, 69219.67),
 (43, 'BUS', 82028.05, 69116.19),
 (34, 'CHQ', 77291.46, 68148.46),
 (170, 'SAV', 69580.12, 67892.68),
 (49, 'SAV', 87557.84, 67597.17),
 (284, 'SAV', 85756.7, 67343.71),
 (216, 'SAV', 74211.19, 66688.05),
 (23, 'CHQ', 86557.7, 66681.54),
 (157, 'CHQ', 73162.44, 66677.95),
 (83, 'CHQ', 76413.7, 65268.73),
 (94, 'SAV', 74260.98, 65103.25),
 (273, 'BUS', 65213.27, 64630.48),
 (274, 'CHQ', 64163.66, 64391.96),
 (85, 'SAV', 69476.72, 63953.12),
 (92, 'BUS', 71552.54, 63695.53),
 (247, 'BUS', 72957.44, 63680.8),
 (114, 'BUS', 67973.27, 61768.25),
 (210, 'CHQ', 68064.25, 61438.11),
 (33, 'CHQ', 66644.17, 61304.48),
 (10, 'BUS', 72667.44, 61295.85),
 (166, 'BUS', 65453.56, 60909.98),
 (175, 'BUS', 70997.62, 60730.8),
 (21, 'CHQ', 61088.32, 60323.48),
 (30, 'CHQ', 63355.07, 60223.66),
 (113, 'CHQ', 82792.58, 59518.34),
 (189, 'SAV', 67788, 59371.67),
 (204, 'CHQ', 72290.49, 59260.44),
 (36, 'BUS', 65482.68, 58765.36),
 (260, 'SAV', 55607.43, 58736.02),
 (254, 'BUS', 63839.93, 58488.13),
 (296, 'CHQ', 65875.84, 58438.33),
 (201, 'CHQ', 60209.26, 58084.55),
 (131, 'CHQ', 65314.36, 57863.14),
 (214, 'CHQ', 61928.33, 57633.61),
 (91, 'BUS', 62531.41, 57416.62),
 (41, 'CHQ', 57835.64, 57104.93),
 (44, 'SAV', 69658.25, 56927),
 (63, 'BUS', 57035.26, 56121.48),
 (256, 'SAV', 72686.41, 56090.32),
 (230, 'SAV', 63379.26, 56000.4),
 (72, 'SAV', 59597.18, 55016.11),
 (126, 'CHQ', 56986.7, 54966.52),
 (224, 'SAV', 61398.87, 54770.46),
 (71, 'CHQ', 52620.44, 53956.77),
 (264, 'BUS', 56998.05, 53926.32),
 (74, 'BUS', 70301.55, 53845.77),
 (257, 'SAV', 69711.29, 53719.87),
 (58, 'CHQ', 58127.71, 53577.61),
 (118, 'CHQ', 57084.45, 52964.36),
 (48, 'SAV', 63416.35, 52843.66),
 (207, 'CHQ', 57012.31, 52528.87),
 (39, 'CHQ', 73214.41, 51564.56),
 (108, 'CHQ', 66088.83, 49951.06),
 (150, 'BUS', 77477.04, 49865.67),
 (98, 'SAV', 69297.68, 49039.24),
 (109, 'CHQ', 56112.34, 48613.06),
 (104, 'CHQ', 58057.6, 48438.74),
 (248, 'SAV', 65919.35, 47998.67),
 (65, 'CHQ', 61400.1, 47822.11),
 (287, 'CHQ', 51492.52, 47474.41),
 (127, 'CHQ', 54938.1, 47324.92),
 (217, 'SAV', 50874.79, 46402.63),
 (54, 'CHQ', 48383.18, 46373.47),
 (243, 'SAV', 49766.04, 45921.83),
 (226, 'CHQ', 55444.17, 44780.04),
 (79, 'CHQ', 49404.4, 44568.86),
 (155, 'SAV', 55474.05, 44417.49),
 (122, 'CHQ', 48725.2, 42894.28),
 (205, 'SAV', 49952.82, 42395.12),
 (60, 'SAV', 53485.04, 42130.36),
 (238, 'BUS', 46680.5, 41855.65),
 (154, 'CHQ', 66605.48, 41687.01),
 (283, 'CHQ', 52820.66, 40851.47),
 (186, 'SAV', 46559.63, 40786.01),
 (159, 'BUS', 44147.62, 40707.78),
 (288, 'CHQ', 51490.77, 40619.52),
 (289, 'CHQ', 41904.46, 40040.34),
 (153, 'CHQ', 50791.28, 39892.29),
 (261, 'SAV', 55402.81, 38692.1),
 (271, 'BUS', 43452.71, 38614.67),
 (278, 'SAV', 48434.8, 38588.1),
 (53, 'SAV', 49101.06, 38562.76),
 (235, 'SAV', 44741.9, 38548.88),
 (177, 'BUS', 52032.61, 38525.96),
 (180, 'BUS', 40624.03, 38174.73),
 (246, 'CHQ', 58063.58, 38057.85),
 (86, 'SAV', 50837.08, 37575.23),
 (156, 'SAV', 41520.57, 37528.58),
 (125, 'SAV', 44498.65, 37121.79),
 (196, 'CHQ', 47316.34, 36998.18),
 (212, 'BUS', 54950.8, 36991.57),
 (51, 'BUS', 45793.34, 36889.09),
 (234, 'BUS', 35041.68, 36177.36),
 (168, 'CHQ', 41877.4, 36041.67),
 (55, 'BUS', 49713.83, 35276.6),
 (213, 'SAV', 41508.56, 34904.59),
 (66, 'CHQ', 40008.53, 34548.21),
 (70, 'SAV', 33716.29, 34215.33),
 (129, 'BUS', 35668.54, 33680.12),
 (62, 'CHQ', 36702.54, 33458.23),
 (116, 'BUS', 34798.47, 33368.1),
 (208, 'CHQ', 39569.33, 33356),
 (285, 'CHQ', 36115.4, 33322.17),
 (68, 'SAV', 37748.82, 33217),
 (295, 'CHQ', 44516.4, 32872.18),
 (169, 'CHQ', 32880.92, 32866.23),
 (294, 'BUS', 36864.46, 32347.84),
 (134, 'SAV', 37690.5, 32309.47),
 (82, 'SAV', 29525.31, 32204.53),
 (179, 'BUS', 42494.67, 32080.66),
 (136, 'CHQ', 32694.57, 31130.27),
 (233, 'CHQ', 46629.3, 29701.8),
 (182, 'CHQ', 29159.33, 28753.98),
 (143, 'SAV', 27480.19, 28504.56),
 (100, 'CHQ', 33128.61, 27420.24),
 (145, 'SAV', 34588.13, 27041),
 (242, 'BUS', 31705.31, 26775.88),
 (90, 'CHQ', 33551.51, 26596.14),
 (163, 'CHQ', 30169.57, 25343.89),
 (87, 'CHQ', 31103.59, 24812.22),
 (152, 'SAV', 31858.67, 24587.76),
 (223, 'SAV', 41345.93, 24368.49),
 (251, 'SAV', 33140.3, 24335.77),
 (280, 'SAV', 45824.72, 24159.2),
 (96, 'SAV', 37055.15, 24087.92),
 (110, 'SAV', 36235.58, 22657.98),
 (167, 'BUS', 20965.26, 22424.96),
 (144, 'CHQ', 31521.61, 22318.58),
 (244, 'CHQ', 30768.43, 22132.66),
 (120, 'SAV', 27253.21, 21193.13),
 (263, 'SAV', 22682.38, 21041.65),
 (181, 'SAV', 24453.37, 20139.47),
 (286, 'CHQ', 25533.43, 19872.15),
 (73, 'CHQ', 27130.9, 19496.87),
 (69, 'SAV', 18172.88, 19195.34),
 (267, 'BUS', 24588.13, 18559.24),
 (236, 'BUS', 23084.55, 18531.61),
 (219, 'BUS', 29672.22, 18376.22),
 (258, 'CHQ', 31874.66, 18283.48),
 (174, 'BUS', 23535.33, 18128.61),
 (185, 'CHQ', 33527.24, 17896.48),
 (112, 'CHQ', 31854.76, 16383.36),
 (255, 'BUS', 29913.6, 16229.53),
 (161, 'CHQ', 22932, 15891.67),
 (99, 'SAV', 17951.51, 15586.95),
 (105, 'CHQ', 27705.29, 15426.47)]

5. (3 points) Please write a SQL query to find the customer ID, first name, and last name of customers who own accounts at London and Berlin branches, order by last name and first name.

In [7]:
%%sql
SELECT C.customerID, firstName, lastName
FROM Customer C, Account A, Branch B, Owns O
WHERE C.customerID = O.customerID 
and O.accNumber = A.accNumber 
and A.branchNumber = B.branchNumber 
and branchName = 'London' 

INTERSECT

SELECT C.customerID, firstName, lastName
FROM Customer C, Account A, Branch B, Owns O
WHERE C.customerID = O.customerID 
and O.accNumber = A.accNumber 
and A.branchNumber = B.branchNumber 
and branchName = 'Berlin'
ORDER BY lastName, firstName

 * sqlite:///bank.db
Done.

[(66418, 'Stephanie', 'Adams'),
 (89197, 'Lawrence', 'Anderson'),
 (41545, 'Terry', 'Bailey'),
 (33726, 'Jerry', 'Cook'),
 (86357, 'Andrew', 'Evans'),
 (44922, 'Dennis', 'Flores'),
 (87978, 'Christopher', 'Gonzalez'),
 (10839, 'Amy', 'Hayes'),
 (99537, 'Deborah', 'Hernandez'),
 (13697, 'Charles', 'Hill'),
 (38861, 'Gerald', 'James'),
 (73386, 'Arthur', 'Jones'),
 (47953, 'Frank', 'Martinez'),
 (88375, 'Randy', 'Mitchell'),
 (90649, 'Helen', 'Morgan'),
 (46058, 'Adam', 'Rivera'),
 (52189, 'Shawn', 'Sanders'),
 (13423, 'Norma', 'Simmons'),
 (65441, 'Arthur', 'Thompson'),
 (29474, 'Amanda', 'White'),
 (63859, 'Maria', 'Young')]

## Submission

Complete the code in this notebook [hw2.ipynb](hw2.ipynb), and submit it to through Canvas system to your HW2 activity. You can also include a pdf file where you can add your comments, thoughts, explanations about any of the questions.